spring.application.name=authservice

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:authservice}
spring.datasource.username=admin
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port = 9895

logging.level.org.springframework.security=DEBUG
logging.level.your.package.name=DEBUG


#kafka Properties
#kafka:9092
spring.kafka.producer.bootstrap-servers=${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
spring.kafka.producer.properties.max.in.flight.requests.per.connection=1
spring.kafka.producer.properties.retries=3
spring.kafka.producer.properties.acks=all
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.authservice.serializer.UserInfoSerializer
spring.kafka.topic-json.name=user_service
spring.kafka.producer.properties.retry.backoff.ms=1000
logging.level.org.apache.kafka=DEBUG
logging.level.org.springframework.kafka=DEBUG
spring.kafka.producer.properties.spring.json.type.mapping=auth:org.authservice.eventProducer.UserInfoEvent
security.basic.enable= false
security.ignored=/**