spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://13.205.147.251:5432/authservice
spring.datasource.username=admin
spring.datasource.password=root


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port = 9898

logging.level.org.springframework.security=DEBUG
logging.level.your.package.name=DEBUG


#kafka Properties
spring.kafka.producer.bootstrap-servers=13.205.147.251:9092
spring.kafka.topic.name=testingself
spring.kafka.topic-json.name=testingself_json
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.example.serializer.UserInfoSerializer
spring.kafka.producer.properties.spring.json.type.mapping=auth:org.example.eventProducer.UserInfoEvent