spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/authservice
spring.datasource.username=admin
spring.datasource.password=root


# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port = 9895

logging.level.org.springframework.security=DEBUG
logging.level.your.package.name=DEBUG


#kafka Properties
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topic-json.name=user_service
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.example.serializer.UserInfoSerializer
spring.kafka.producer.properties.spring.json.type.mapping=auth:org.example.eventProducer.Use
spring.kafka.producer.properties.retries=10
spring.kafka.producer.properties.retry.backoff.ms=1000