/*
 * This source file was generated by the Gradle 'init' task
 */
package org.authservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.core.env.ConfigurableEnvironment;

import java.util.Arrays;


@SpringBootApplication
public class App {
    public static void main(String[] args) {

        ConfigurableApplicationContext run = SpringApplication.run(App.class, args);
        ConfigurableEnvironment environment = run.getEnvironment();
        String[] activeProfiles = environment.getActiveProfiles();
        Arrays.stream(activeProfiles).forEach(System.out::println);
    }
}
